<table border="1">
    <tr>
        <th>createdate_jira</th>
        <th>task_link</th>
        <th>dealine</th>
        <th>short_description</th>
        <th>estimated_time</th>
        <th>total_time</th>
        <th>pm_employee</th>
        <th>employee</th>
        <th>pm_employee_time_total</th>
        <th>employee_time_total</th>
        <th>tester</th>
        <th>author</th>
        <th>status</th>
        <th>real_deadline</th>
        <th>p_id</th>
        <th>p_id_nr</th>
        <th>kva_id_paid</th>
        <th>customer_task_raiting</th>
    </tr>
    @isset($tasks)
        @foreach ($tasks as $task)
            <tr>
                <td>{{$task->createdate_jira}}</td>
                <td>{{$task->task_link}}</td>
                <td>{{$task->dealine}}</td>
                <td>{{$task->short_description}}</td>
                <td>{{$task->estimated_time}}</td>
                <td>{{$task->total_time}}</td>
                <td>{{$task->pm_employee}}</td>
                <td>{{$task->employee}}</td>
                <td>{{$task->pm_employee_time_total}}</td>
                <td>{{$task->employee_time_total}}</td>
                <td>{{$task->tester}}</td>
                <td>{{$task->author}}</td>
                <td>{{$task->status}}</td>
                <td>{{$task->real_deadline}}</td>
                <td>{{$task->p_id}}</td>
                <td>{{$task->p_id_nr}}</td>
                <td>{{$task->kva_id_paid}}</td>
                <td>{{$task->customer_task_raiting}}</td>
            </tr>
        @endforeach
    @endisset
</table>
